ALTER TABLE kp_users
  ADD COLUMN IF NOT EXISTS saved_address_line1 TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS saved_suburb TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS saved_state TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS saved_postcode TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS saved_country TEXT NOT NULL DEFAULT '';
